name: test

on:
  repository_dispatch:
   types: [setup]
  
jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run the Another Workflow
        run: |
          echo "Running another workflow"







